### ISSUE TITLE
Capture Permissions In Bundle's Module File

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/cu_digital_campaign_bundle#1]
This bundle still has the Forms bundle's permissions and function names in the main bundle's .module file. 

With all of the module's enabled in this bundle, new permissions need to be captured or else no one will be able to view or use the code.

**Comment by kreynen** [comment]
The permissions have been manually set on https://www.colorado.edu/graduateschool/admin/people/permissions, but we need to define who is going to be able to use this functionality before we capture the settings https://github.com/CuBoulder/express/issues/1062

**Comment by alexfinnarn** [comment]
Regardless of whatever the final permissions are, the module's function names need changing or else a site will fatal if it already has the forms bundle enabled. 

The code is only deployed on the graduate school site, and the digital_campaign_bundle module isn't enabled. I don't know where else the code could be deployed.

**Comment by alexfinnarn** [comment]
Permissions added to master branch.
